### ISSUE TITLE
Access-Control-Allow-Origin: Not allowed

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/typo3-easydb-plugin#1]
Wenn ich meine lokale URL eintrage kriege ich beim "Übernehmen in Typo3" diesen Fehler:

XMLHttpRequest cannot load https://easydb.helhum.io/typo3/index.php?ajaxID=%2Fajax%2Feasydb%2Fimport&id=1%3A%2Fuser_upload%2FSTest%2F&importToken=ab7331e471e19f67c9fa845a49100c4e9c932e25. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.150.0.4' is therefore not allowed access. The response had HTTP status code 500.

**Comment by helhum** [comment]
Kannst Du einen Screenshot hinzufügen mit dem was Du genau konfiguriert hast?

**Comment by martinrode** [comment]
habe den fehler aktuell nicht mehr
