### ISSUE TITLE
Meta data fields are not updated after re-import

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#10]
> Nach dem Update ist keine Aktualisierung des Datensatzes mehr möglich. Kein Feld wurde nach einer Änderung in TYPO3 aktualisiert. Auch ein mehrfaches übertragen half an dieser Stelle nicht. Erst ein Schließen des EasyDB-Fensters und erneutes Importieren über die Schaltfläche „Add files from easydb“ half. 

I cannot reproduce this. @datango Any hints how I can reproduce this? What exactly where the steps you tried?

**Comment by datango** [comment]
Updating multiple Fields in EasyDB are now correctly updated in TYPO3. EasyDB asks (also if EasyDB window is allready open) if the Element should be overwritten.

**Comment by helhum** [comment]
Can be closed then
