### ISSUE TITLE
Existing files are not properly recorded by easydb

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#11]
TYPO3 sends the list of existing files as map in the file picker URL as key `existing_files`

However, when selecting re-importing an already imported file, easydb does not recognize it as existing, when the window is just opened.

However when the filepicker window stays open and one file is imported a second time, the file is recognized as already present.

Any hints @martinrode?

**Comment by datango** [comment]
I only get the message "Einige Dateien existieren bereits im Zielverzeichnis" if i reimport an existing EasyDB element a second time with the already opened EasyDB window.

**Comment by helhum** [comment]
> I only get the message "Einige Dateien existieren bereits im Zielverzeichnis" if i reimport an existing EasyDB element a second time with the already opened EasyDB window.

Can confirm that. @martinrode should have a look at this

**Comment by martinrode** [comment]
Das ist ein Fehler im Typo3 Plugin.

Das Plugin sendet:

```
existing_files: [
  {
   "9f159cbd-e247-4d43-887f-68ba7d254758/1000672565/original": "9f159cbd-e247-4d43-887f-68ba7d254758/1000672565/original"
  }
]
```

es muss aber:

```
existing_files: [
  {
   "uidl": "9f159cbd-e247-4d43-887f-68ba7d254758/1000672565/original"
  }
]
```

schicken.

in der spec steht: "Map mit Key **uid** und als Value die uid."

**Comment by helhum** [comment]
Ahhh. The string `uid` or `uidl`?

**Comment by martinrode** [comment]
> Ahhh. The string `uid` or `uidl`?

Typo im Comment, korrigiert. "uid"

**Comment by helhum** [comment]
Thanks. Fixed
