### ISSUE TITLE
Static text mappings (e.g. UNDFx) are ignored

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#12]
Since I have no clue about this easydb feature, can anybody of you (e.g. @martinrode) elaborate?

**Comment by datango** [comment]
In the TYPO3 mapping i try to use static text:

![grafik](https://user-images.githubusercontent.com/30523869/61050949-7314e480-a3e8-11e9-89e9-1a99f14f7bd2.png)

which is not stored to TYPO3 field.

**Comment by martinrode** [comment]
peter, kannst du dir das hier bitte mal anschauen?

**Comment by martinrode** [comment]
Ok, der Bug ist da. Wir schauen uns das weiter an.

**Comment by martinrode** [comment]
5.55.0., Release vom 14.8. hat den Fixed Mapping Bug gefixt. Wichtig: Das Metadatenprofil muss neu gespeichert werden. Kann getestet werden.

**Comment by helhum** [comment]
Works now with latest easydb server update (issue was unrelated to TYPO3 integration extension)
