### ISSUE TITLE
Default language contains all translations with locale identifiers

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#13]
![image003](https://user-images.githubusercontent.com/904370/60980848-86b34300-a335-11e9-84d8-dfaabd29950a.png)

Since this likely is something where easydb does not send well formed meta data to TYPO3, I guess this needs to be tackled on easydb side. Any hints @martinrode?

**Comment by martinrode** [comment]
Lass uns hier mal auf Deutsch weitermachen:

easydb schickt sowas hier bei einem POST.

Das ist exakt wie wir das in der Spec haben. Was sonst erwartest du hier?


```
{
	"files": [
		{
			"asset_id": 1001996427,
			"asset_version": "small",
			"system_object_id": 166,
			"objecttype": "bilder",
			"object_id": 164,
			"object_version": 5,
			"uuid": "a03f02e0-385d-4f59-87fe-d5581b59fef8",
			"uid": "a03f02e0-385d-4f59-87fe-d5581b59fef8/1001996427/small",
			"event": {
				"objecttype": "bilder",
				"object_id": 164,
				"object_version": 5,
				"schema": "USER",
				"info": {
					"asset": {
						"id": 1001996427,
						"version": "small",
						"filesize": 42248,
						"filename": "assets/Refe_54e6490c40052_SplitShire_IMG_3142.jpg"
					}
				}
			},
			"filename": "Refe_54e6490c40052_SplitShire_IMG_3142.jpg",
			"url": "https://master.5.easydb.de/api/v1/export/669/download/8de9313c-ed4e-44cd-856e-124e797fd114/166/assets/Refe_54e6490c40052_SplitShire_IMG_3142.jpg",
			"title": {
				"de-DE": "CC0 Bilder",
				"en-US": "CC0 Images"
			},
			"description": {
				"de-DE": "Beschreibung",
				"en-US": "Description"
			}
		}
	],
	"window_preferences": {
		"width": 1321,
		"height": 834
	},
	"send_data": false
}
```

**Comment by helhum** [comment]
In my tests I am receiving a json like that and it is properly imported for all files I tested with.

Since I have no access to this particular easydb instance, thus am not able to see what json structure it exactly sends, it is hard for me to tell how the json structure got imported into the keywords field in TYPO3.

How do we proceed here?

**Comment by martinrode** [comment]
Wenn du von Deiner Testinstanz arbeitest kommst du doch auf diei easydb Testinstanz oder? Login/Pw solltest du ja haben.

**Comment by helhum** [comment]
With the changes in easydb, this works now in my tests
