### ISSUE TITLE
Send files over browser seems broken

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#15]
When changing the settings so that files are sent via the browser, no POST data is submitted to TYPO3, thus import currently fails.

I guess this needs some fix on the easydb server side

**Comment by martinrode** [comment]
Works in my test. However, this did not work with the system object id 3, as it did not send a filename. so the filename was ".jpg". typo3 plugin said ".jpg" received but did not show a file. when i sent this file the second time, a "_01.jpg" was stored.

**Comment by helhum** [comment]
Mistake on my side. The PHP POST max size was configured to low for the file size that I wanted to import, thus PHP silently discarded the POST data...
