### ISSUE TITLE
Übernehmen von "unerreichbaren Dateien"

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/typo3-easydb-plugin#2]
Passiert wenn man Dateien schickt, die eine unerreichbare URL beinhalten.

- Das soll nicht sein, es muss ein CSV Fehler kommen (JSON formatiert), jetzt kommt immer Allow-Origin Fehler

TYPO3 logo
Oops, an error occurred!

TYPO3 CMS is an open source content management system. To maintain the quality of the system and to improve it, please help us by donating. TYPO3 CMS. Copyright © 1998-2017 Kasper Skårhøj. Extensions are copyright of their respective owners. Go to https:typo3.org/ for details. TYPO3 CMS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions. Obstructing the appearance of this notice is prohibited by law.

**Comment by helhum** [comment]
Kannst Du kurz erläutern wie ich das reproduzieren kann?

**Comment by martinrode** [comment]
Ich habe einfach mit meiner lokalen Instanz getestet mit Base Config Einstellungen "Dateien über das Frontend versenden" auf "aus". Damit hat der Typo3 Server den easydb Server nicht erreicht und konnte die URLs nicht holen. Um das zu testen würde ich das ggfs faken, d.h. du machst einfach die URLs kaputt...

**Comment by martinrode** [comment]
1) Wenn die Bilder schon bekannt sind, versucht das PHP die URL zu erreichen und nach ca. 20 Sekunden ohne Fehler aufgibt. Der Server antwortete in einem Fall mit einem Update. Das soll nicht sein, der Server muss einen Fehler werfen. Er kann ein Update in dem Fall machen, wenn keine URL gesendet wurde. Im Falle des Updates sind leere Bilder im Typo3.

2)  Wenn die Bilder noch nicht da sind, antwortet PHP sehr schnell (vielleicht wurde die URL gechacht?) und quittiert mit eine "insert", was nicht sein kann, da die Bilder nicht erreichbar sind. Es werden zwei leere Bilder erzeugt.

Request war: ajaxID=%2Fajax%2Feasydb%2Fimport&id=1%3A%2Fuser_upload%2FSTest%2F&importToken=13ddf4ff1013e5392c5e868b5cc4b53ffd7c694b

Payload:

`------WebKitFormBoundaryK1TU86Vohq6Egumd
Content-Disposition: form-data; name="body"

{"files":[{"url":"http://10.150.0.4/api/v1/export/94/download/402cfabd-4307-4ae6-a783-ca646f60440d/15/assets/15@f92c6b02-a816-4018-bdf7-5f12f1286ac8_418_small.jpg","path":"402cfabd-4307-4ae6-a783-ca646f60440d/15/assets/15@f92c6b02-a816-4018-bdf7-5f12f1286ac8_418_small.jpg","asset_id":418,"uid":"5c027c69-f4bc-4de2-9ab1-97c48ea56396/418/small","event":{"objecttype":"bilder","object_id":2,"object_version":1,"schema":"USER","info":{"asset":{"id":418,"version":"small","filesize":44111,"filename":"15/assets/15@f92c6b02-a816-4018-bdf7-5f12f1286ac8_418_small.jpg"}}},"filename":"15@f92c6b02-a816-4018-bdf7-5f12f1286ac8_418_small.jpg","title":{"de-DE":"Titel DE","en-US":"Titel EN"},"description":{"de-DE":"Beschreibung DE","en-US":"Beschreibung US"},"keywords":[{"de-DE":"Schlag A","en-US":"Schlag A"},{"de-DE":"Schlag B","en-US":"Schlag B"}],"copyright":"Vermerk"},{"url":"http://10.150.0.4/api/v1/export/94/download/402cfabd-4307-4ae6-a783-ca646f60440d/6/assets/6@f92c6b02-a816-4018-bdf7-5f12f1286ac8_412_small.jpg","path":"402cfabd-4307-4ae6-a783-ca646f60440d/6/assets/6@f92c6b02-a816-4018-bdf7-5f12f1286ac8_412_small.jpg","asset_id":412,"uid":"b2737dfe-e0ae-4c78-9e06-789ef0d496e4/412/small","event":{"objecttype":"bilder","object_id":1,"object_version":7,"schema":"USER","info":{"asset":{"id":412,"version":"small","filesize":56486,"filename":"6/assets/6@f92c6b02-a816-4018-bdf7-5f12f1286ac8_412_small.jpg"}}},"filename":"6@f92c6b02-a816-4018-bdf7-5f12f1286ac8_412_small.jpg","title":{"de-DE":"Titel DE","en-US":"Titel EN"},"description":{"de-DE":"Beschreibung DE","en-US":"Beschreibung US"},"keywords":[{"de-DE":"Schlag A","en-US":"Schlag A"},{"de-DE":"Schlag B","en-US":"Schlag B"}],"copyright":"Vermerk"}],"window_preferences":{"width":1282,"height":705},"send_data":false}
------WebKitFormBoundaryK1TU86Vohq6Egumd--`


Response: `
{"files":[{"uid":"5c027c69-f4bc-4de2-9ab1-97c48ea56396\/418\/small","url":"https:\/\/easydb.helhum.io\/typo3\/fileadmin\/user_upload\/STest\/15%40f92c6b02-a816-4018-bdf7-5f12f1286ac8_418_small.jpg","resourceid":53,"status":"done","action_taken":"insert"},{"uid":"b2737dfe-e0ae-4c78-9e06-789ef0d496e4\/412\/small","url":"https:\/\/easydb.helhum.io\/typo3\/fileadmin\/user_upload\/STest\/6%40f92c6b02-a816-4018-bdf7-5f12f1286ac8_412_small.jpg","resourceid":54,"status":"done","action_taken":"insert"}],"took":294}`

**Comment by martinrode** [comment]
Das Ticket hier ist alt, ich mache es zu und ggfs machen wir es neu auf.
