### ISSUE TITLE
feature request: display condition for button in filelist

### ISSUE THREAD

**Issue by urz-hgw** [programmfabrik/typo3-easydb-plugin#21]
We are running a multidomain/-instance of TYPO3 for many universities. Not all of them are using easydb or the import-feature.
It would be nice to have some display conditions for the easydb-import button in the filelist.

Our approach is to check a usertsconfig like `options.file_list.enableEasydbImport = 1` inside https://github.com/programmfabrik/typo3-easydb-plugin/blob/571dd946da1cd2e993f9227f9a0bac368625fe53/Classes/Hook/FileListButtonHook.php#L104 e.g.

```php
public function getButtons(array $params, ButtonBar $buttonBar)
    {
        $buttons = $params['buttons'];
        $userTsConfig = $GLOBALS['BE_USER']->getTSConfig();
        // Only add the button to file list module and allowes users/groups
        if (!$this->isFileListModuleUri() OR !$userTsConfig['options.']['file_list.']['enableEasydbImport']) {
            return $buttons;
        }
[...]
```

Could you please implement a feature like this?

-- Arne

**Comment by KlausThornProgrammfabrik** [comment]
Thanks for reaching out.

Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.

> We are running a multidomain/-instance of TYPO3 for many universities. Not all of them are using easydb or the import-feature. It would be nice to have some display conditions for the easydb-import button in the filelist.
> 
> Our approach is to check a usertsconfig like `options.file_list.enableEasydbImport = 1` inside
> 
> https://github.com/programmfabrik/typo3-easydb-plugin/blob/571dd946da1cd2e993f9227f9a0bac368625fe53/Classes/Hook/FileListButtonHook.php#L104
> 
> e.g.
> ```
> public function getButtons(array $params, ButtonBar $buttonBar)
>     {
>         $buttons = $params['buttons'];
>         $userTsConfig = $GLOBALS['BE_USER']->getTSConfig();
>         // Only add the button to file list module and allowes users/groups
>         if (!$this->isFileListModuleUri() OR !$userTsConfig['options.']['file_list.']['enableEasydbImport']) {
>             return $buttons;
>         }
> [...]
> ```
> 
> Could you please implement a feature like this?
> 
> -- Arne
