### ISSUE TITLE
TYPO3 V11 Support

### ISSUE THREAD

**Issue by flolanger** [programmfabrik/typo3-easydb-plugin#22]
Hi,

it would be really nice to have this extension also available for the latest TYPO3 V11 LTS version and PHP 8.0.

**Comment by fzuerker** [comment]
Hi all,
with PHP 7.4 going EOL later this year, is there any news on TYPO3 v11 support for this extension?

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.

As a side note, this extension is to be released for newer Typo3 versions, yes. We try to contract https://github.com/helhum for this and if you politely tell him how relevant this is for you, things might speed up.
