### ISSUE TITLE
Mehrsprachigkeit easydb Typo3 Plugin

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/typo3-easydb-plugin#6]
Das Mapping:

1. Der Import der Datei klappt immer. Die Übernahme der Metadaten erst, wenn ich die Daten ein zweites Mal importiere (überschreibe). Vorher sind die Metadaten leer. Es existiert dann auch nur die DE-Sprachversion und keine EN-Version. Letztere wird erst bei einem Update/Überschreiben der Datei angelegt.

2. Nach dem Update ist keine Aktualisierung des Datensatzes mehr möglich. Kein Feld wurde nach einer Änderung in TYPO3 aktualisiert. Auch ein mehrfaches übertragen half an dieser Stelle nicht. Erst ein Schließen des EasyDB-Fensters und erneutes Importieren über die Schaltfläche „Add files from easydb“ half. Interessanter Weise kam dann kein Hinweis, dass die Datei überschrieben würde.

3. Die statischen Text-Mappings (hier „UNDFx“) werden ignoriert.

4. Mehrfachfelder werden nicht sinnvoll übernommen. Was ist hier zu tun? Ich würde gerne Mehrfachfelder z.B. für Schlagwörter verwenden um dann eine Liste (mit Trennzeichen Leerzeichen/Komme) zu erzeugen.

5. Standardsprache enthält (vermutlich zum Testen) beide Sprachversionen mit dem entsprechenden Sprachenbezeichner davor (siehe unten)

6. Kein automatischer Refresh der Fileadmin-Seite. Ich muss manuell die Seite aktualisieren, um neue Dateien zu sehen.

7. Übernahme eines Feldes mit verknüpftem Datensatz funktioniert nicht

**Comment by helhum** [comment]
> Der Import der Datei klappt immer. Die Übernahme der Metadaten erst, wenn ich die Daten ein zweites Mal importiere (überschreibe). Vorher sind die Metadaten leer. Es existiert dann auch nur die DE-Sprachversion und keine EN-Version. Letztere wird erst bei einem Update/Überschreiben der Datei angelegt.

See: #7

**Comment by helhum** [comment]
> Kein automatischer Refresh der Fileadmin-Seite. Ich muss manuell die Seite aktualisieren, um neue Dateien zu sehen.

See: #8

**Comment by helhum** [comment]
> Mehrfachfelder werden nicht sinnvoll übernommen. Was ist hier zu tun? Ich würde gerne Mehrfachfelder z.B. für Schlagwörter verwenden um dann eine Liste (mit Trennzeichen Leerzeichen/Komme) zu erzeugen.

See: #9

**Comment by helhum** [comment]
> Nach dem Update ist keine Aktualisierung des Datensatzes mehr möglich. Kein Feld wurde nach einer Änderung in TYPO3 aktualisiert. Auch ein mehrfaches übertragen half an dieser Stelle nicht. Erst ein Schließen des EasyDB-Fensters und erneutes Importieren über die Schaltfläche „Add files from easydb“ half. Interessanter Weise kam dann kein Hinweis, dass die Datei überschrieben würde.

See: #10 and #11

**Comment by helhum** [comment]
> Die statischen Text-Mappings (hier „UNDFx“) werden ignoriert.

See: #12

**Comment by helhum** [comment]
> Standardsprache enthält (vermutlich zum Testen) beide Sprachversionen mit dem entsprechenden Sprachenbezeichner davor

See: #13

**Comment by helhum** [comment]
> Übernahme eines Feldes mit verknüpftem Datensatz funktioniert nicht

See: #14

**Comment by helhum** [comment]
This is a meta ticket, which can now be closed. Last remaining open issue (yet to be verified whether this works) is #12
