### ISSUE TITLE
Importing Files with multiple translations fails

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#7]
Because TYPO3's DataHandler does not allow translations of one record multiple times during one request, importing of meta data fails when more than one translation must be created.

**Comment by helhum** [comment]
Fixed with c27cd4c

**Comment by datango** [comment]
Importing multi language element (de/us) from EasyDB works now. The translations for default, en and de are set correctly. For default language there ist currently a debug output like de-DE: Das ist DE , en-US: That is EN. This should be DE.

**Comment by helhum** [comment]
> For default language there ist currently a debug output like de-DE: Das ist DE , en-US: That is EN. This should be DE.

I think I have a dedicated ticket #13 for that issue. Since I cannot reproduce it in my test instance, maybe @martinrode has an idea. But let's continue discussion in that other ticket
