### ISSUE TITLE
Tags are not properly imported

### ISSUE THREAD

**Issue by helhum** [programmfabrik/typo3-easydb-plugin#9]
![image003](https://user-images.githubusercontent.com/904370/60979941-d7c23780-a333-11e9-8b26-bbec0dd261fc.png)

@martinrode I have no clue what happens here, since during my tests tags are not submitted to TYPO3 at all. Can you have a look, what needs to be changed on easydb side that tags are submitted?

**Comment by martinrode** [comment]
Tags sind nicht Teil der SPEC und werden nicht mit ins Typo3 gepostet.

**Comment by helhum** [comment]
same here. tags are properly exposed by easydb now
